const types = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    ADMIN_LOGIN_REQUEST: 'ADMIN_LOGIN_REQUEST',
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    CLIENT_REQUEST: 'REGISTER_REQUEST',
    CLIENT_SUCCESS: 'REGISTER_SUCCESS',
    CLIENT_FAIL: 'REGISTER_FAIL',
    FETCH_CLIENTS_REQUEST: ' FETCH_CLIENTS_REQUEST',
    FETCH_CLIENTS_SUCCESS: 'FETCH_CLIENTS_SUCCESS',
    FETCH_CLIENTS_FAIL: 'FETCH_CLIENTS_FAIL',
    FETCH_CLIENT_REQUEST: 'FETCH_CLIENT_REQUEST',
    FETCH_CLIENT_SUCCESS: 'FETCH_CLIENT_SUCCESS',
    FETCH_CLIENT_FAIL: 'FETCH_CLIENT_FAIL',
    DELETE_CLIENT_REQUEST: 'DELETE_CLIENT_REQUEST',
    DELETE_CLIENT_SUCCESS: 'DELETE_CLIENT_SUCCESS',
    DELETE_CLIENT_FAIL: 'DELETE_CLIENT_FAIL',
    UPDATE_CLIENT_REQUEST: 'UPDATE_CLIENT_REQUEST',
    UPDATE_CLIENT_SUCCESS: 'UPDATE_CLIENT_SUCCESS',
    UPDATE_CLIENT_FAIL: 'UPDATE_CLIENT_FAIL',
   // adding request
    ADD_LEAVE_REQUEST: 'ADD_LEAVE_REQUEST',
    ADD_LEAVE_SUCCESS: 'ADD_LEAVE_SUCCESS',
    ADD_LEAVE_FAIL: 'ADD_LEAVE_FAIL',

    // fetching leave list
    FETCH_LEAVE_REQUEST: 'FETCH_LEAVE_REQUEST',
    FETCH_LEAVE_SUCCESS: 'FETCH_LEAVE_SUCCESS',
    FETCH_LEAVE_FAIL: 'FETCH_LEAVE_FAIL',
    SET_USER:'SET_USER',
    ADD_TO_CART : 'ADD_TO_CART',

    // REVIEW Leave request
    REVIEW_LEAVE_REQUEST: 'REVIEW_LEAVE_REQUEST',
    REVIEW_LEAVE_SUCCESS: 'REVIEW_LEAVE_SUCCESS',
    REVIEW_LEAVE_FAIL: 'REVIEW_LEAVE_FAIL',

    LOGOUT: 'LOGOUT',
};

export default types;
