const types = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    CLIENT_REQUEST: 'REGISTER_REQUEST',
    CLIENT_SUCCESS: 'REGISTER_SUCCESS',
    CLIENT_FAIL: 'REGISTER_FAIL',
    FETCH_CLIENTS_REQUEST: ' FETCH_CLIENTS_REQUEST',
    FETCH_CLIENTS_SUCCESS: 'FETCH_CLIENTS_SUCCESS',
    FETCH_CLIENTS_FAIL: 'FETCH_CLIENTS_FAIL',
    LOGOUT: 'LOGOUT',
};

export default types;
